### ISSUE TITLE
Add PHI Verbiage to Getting Started Page

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#47]
Add information to the Getting Started page about, "if you have requested a PHI account, please see our PHI Quickstart. You will be limited to using the following servers with elevated auditing and logging enabled... blah blah blah"

**Comment by HenrikBengtsson** [comment]
Since a month or so, <https://wynton.ucsf.edu/hpc/get-started/access-cluster.html> shows:

![image](https://github.com/ucsf-wynton/wynton-website-hpc/assets/1616850/70d321f5-3283-4748-877f-eda18ad0a1a3)

I also just added support for setting a `?phi=true` URL parameter (#132).  Thus, if we send new PHI-users to <https://wynton.ucsf.edu/hpc/get-started/phi-quickstart.html?phi=true> (e.g. in the welcome email), they will browse the Wynton website in PHI-mode from there on.
