### ISSUE TITLE
Log in without Password

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#56]
The example instructions on the Login without Password page are from MacOS or Unix.

https://wynton.ucsf.edu/hpc/howto/log-in-without-pwd.html

They do not work on Windows.

Make it obvious to readers that the instructions are from MacOS or Linux and that they will need to adapt the instructions to their operating system or ssh client.

**Comment by ellestad** [comment]
You should probably take Windows 10 out of , "These instructions are primarily written for Linux, macOS, and Windows 10 users". Apparently the mkdir command doesn't work as advertised.

**Comment by HenrikBengtsson** [comment]
Oh, forgot about those "basic" commands, but the `ssh` and `ssh-keygen` commands should work, correct?

If the user is on Windows 10, I think we should get them to use the built-in SSH, rather than directing them to PuTTY.

**Comment by HenrikBengtsson** [comment]
Turns out `ssh-keygen` creates `~/.ssh/`, if missing.  This allowed to be to move down that intro section on setting proper file permissions on `~/.ssh/` to the Appendix.  There I clarify those instructions are only for Linux and macOS.

Hopefully, this works for most Windows 10 users and is less confusion.

**Comment by HenrikBengtsson** [comment]
@ellestad, can I close, or do you think there's more that can be done here?

**Comment by ellestad** [comment]
Glad you could simplify it. I'll close.
