### ISSUE TITLE
Remove Banner

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#83]
I'm not sure where this banner is coming from, but it can now be removed.

"Wynton HPC experiences significant issues"
"Cluster access has been disabled and all running jobs have been terminated to minimize risk for file-system corruption"

You might want to add a current alert, something like, "Available CPU cores may be limited as we deal with any casualties from the power outage."

**Comment by HenrikBengtsson** [comment]
The status banner is configured in https://github.com/ucsf-wynton/wynton-website-hpc/blob/master/docs/_data/status.yml.  If it's level is `danger`, then it becomes site-wide (=on all pages), otherwise it's only on https://wynton.ucsf.edu/hpc/status/.  If its level is `info`, then there's no banner at all.

I've lowered the level from `danger` to `info` and I've changed the message, cf. https://github.com/ucsf-wynton/wynton-website-hpc/commit/9051bbd69e6893f6ee4e86d8d2ebe872fc63b4aa
